name: plugin

on:
  push:
    branches:
      - main
      - master

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Build the plugin
      run: gradle plantuml-parser-plugin:buildPlugin
    
    - name: Verify plugin
      id: verify
      uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest
      with:
        ide-versions: |
          ideaIC:2020.1
          ideaIC:2020.2
          ideaIC:LATEST-EAP-SNAPSHOT
    
    - name: Print verify contents
      run: |
        echo "The log file path is: ${{steps.verify.outputs.verification-output-log-filename}}" ;
        cat ${{steps.verify.outputs.verification-output-log-filename}}
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        # TODO: This uploads a zip called `distributions`; see what we can do to just upload the produced plugin itself.
        name: plantuml-parser
        path: plantuml-parser-plugin/build/distributions/plantuml-parser-*.*.*.zip
